// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';


function bonus(x) {
  return {
          value: x
        };
}

function init(param) {
  return {
          strength: 10,
          dexterity: 10,
          constitution: 10,
          intelligence: 10,
          wisdom: 10,
          charisma: 10
        };
}

var Abilities = {
  init: init
};

function Race(BS, BD, BC, BI, BW, BCh) {
  var name = function (character) {
    return character.name;
  };
  var make = function (name) {
    return {
            name: name,
            abilities: {
              strength: 10,
              dexterity: 10,
              constitution: 10,
              intelligence: 10,
              wisdom: 10,
              charisma: 10
            }
          };
  };
  return {
          name: name,
          make: make
        };
}

var Dwarf = (function (param) {
      var name = function (character) {
        return character.name;
      };
      var make = function (name) {
        return {
                name: name,
                abilities: {
                  strength: 10,
                  dexterity: 10,
                  constitution: 10,
                  intelligence: 10,
                  wisdom: 10,
                  charisma: 10
                }
              };
      };
      return {
              name: name,
              make: make
            };
    })({
      value: 0
    });

exports.bonus = bonus;
exports.Abilities = Abilities;
exports.Race = Race;
exports.Dwarf = Dwarf;
/* Dwarf Not a pure module */
