// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';


function init(param) {
  return {
          strength: 10,
          dexterity: 10,
          constitution: 10,
          intelligence: 10,
          wisdom: 10,
          charisma: 10
        };
}

var Abilities = {
  init: init
};

function name(dwarf) {
  return dwarf.name;
}

function make(name) {
  return {
          name: name,
          abilities: {
            strength: 10,
            dexterity: 10,
            constitution: 10,
            intelligence: 10,
            wisdom: 10,
            charisma: 10
          }
        };
}

var DwarfImpl = {
  name: name,
  make: make
};

function name$1(elf) {
  return elf.name;
}

function make$1(name) {
  return {
          name: name,
          abilities: {
            strength: 10,
            dexterity: 10,
            constitution: 10,
            intelligence: 10,
            wisdom: 10,
            charisma: 10
          }
        };
}

var ElfImpl = {
  name: name$1,
  make: make$1
};

function bonus(x) {
  return {
          value: x
        };
}

var bonus_2 = {
  value: 2
};

var default_bonus = {
  value: 0
};

function get_bonus(b) {
  return b.value;
}

function Race(B) {
  var name = function (character) {
    return character.name;
  };
  var make = function (name) {
    return {
            name: name,
            abilities: {
              strength: 10,
              dexterity: 10,
              constitution: 10,
              intelligence: 10,
              wisdom: 10,
              charisma: 10
            }
          };
  };
  return {
          name: name,
          make: make
        };
}

function name$2(character) {
  return character.name;
}

function make$2(name) {
  return {
          name: name,
          abilities: {
            strength: 10,
            dexterity: 10,
            constitution: 10,
            intelligence: 10,
            wisdom: 10,
            charisma: 10
          }
        };
}

var Dwarf = {
  name: name$2,
  make: make$2
};

function name$3(character) {
  return character.name;
}

function make$3(name) {
  return {
          name: name,
          abilities: {
            strength: 10,
            dexterity: 10,
            constitution: 10,
            intelligence: 10,
            wisdom: 10,
            charisma: 10
          }
        };
}

var Elf = {
  name: name$3,
  make: make$3
};

function name$4(character) {
  return character.name;
}

function make$4(name) {
  return {
          name: name,
          abilities: {
            strength: 10,
            dexterity: 10,
            constitution: 10,
            intelligence: 10,
            wisdom: 10,
            charisma: 10
          }
        };
}

var Tiefling = {
  name: name$4,
  make: make$4
};

function name$5(character) {
  return character.name;
}

function make$5(name) {
  return {
          name: name,
          abilities: {
            strength: 10,
            dexterity: 10,
            constitution: 10,
            intelligence: 10,
            wisdom: 10,
            charisma: 10
          }
        };
}

var Halfling = {
  name: name$5,
  make: make$5
};

function name$6(character) {
  return character.name;
}

function make$6(name) {
  return {
          name: name,
          abilities: {
            strength: 10,
            dexterity: 10,
            constitution: 10,
            intelligence: 10,
            wisdom: 10,
            charisma: 10
          }
        };
}

var HalfOrc = {
  name: name$6,
  make: make$6
};

exports.Abilities = Abilities;
exports.DwarfImpl = DwarfImpl;
exports.ElfImpl = ElfImpl;
exports.bonus = bonus;
exports.bonus_2 = bonus_2;
exports.default_bonus = default_bonus;
exports.get_bonus = get_bonus;
exports.Race = Race;
exports.Dwarf = Dwarf;
exports.Elf = Elf;
exports.Tiefling = Tiefling;
exports.Halfling = Halfling;
exports.HalfOrc = HalfOrc;
/* No side effect */
